[desktop]
secret_key=secret_efrei_project_key_2026

[beeswax]
# L'hôte et le port de ton Hive-Server
hive_server_host=hive-server
hive_server_port=10000

# FIX PROTOCOLE : Force Hue à utiliser la version Thrift compatible avec Hive 2.3.2
thrift_version=7

# Désactive l'usurpation d'identité proxy qui déclenchait l'erreur
hive_server_proxy_user=False

[hadoop]
[[hdfs_clusters]]
[[[default]]]
fs_defaultfs=hdfs://namenode:9000
webhdfs_url=http://namenode:9870/webhdfs/v1